/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as UserManagementRouteImport } from './routes/user-management'
import { Route as TeamsRouteImport } from './routes/teams'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as ScheduleRouteImport } from './routes/schedule'
import { Route as RoleManagementRouteImport } from './routes/role-management'
import { Route as RevenueRouteImport } from './routes/revenue'
import { Route as ReportsRouteImport } from './routes/reports'
import { Route as ProgressRouteImport } from './routes/progress'
import { Route as MyAthletesRouteImport } from './routes/my-athletes'
import { Route as LoginRouteImport } from './routes/login'
import { Route as InsightsRouteImport } from './routes/insights'
import { Route as EvaluationsRouteImport } from './routes/evaluations'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as CoachesRouteImport } from './routes/coaches'
import { Route as CoachFeedbackRouteImport } from './routes/coach-feedback'
import { Route as AttendanceRouteImport } from './routes/attendance'
import { Route as IndexRouteImport } from './routes/index'
import { Route as TrainingIndexRouteImport } from './routes/training.index'
import { Route as ProgramsIndexRouteImport } from './routes/programs.index'
import { Route as PaymentsIndexRouteImport } from './routes/payments.index'
import { Route as MatchPerformanceIndexRouteImport } from './routes/match-performance.index'
import { Route as DrillsIndexRouteImport } from './routes/drills.index'
import { Route as AthletesIndexRouteImport } from './routes/athletes.index'
import { Route as AssessmentIndexRouteImport } from './routes/assessment.index'
import { Route as TrainingSessionIdRouteImport } from './routes/training.$sessionId'
import { Route as ProgramsNewRouteImport } from './routes/programs.new'
import { Route as PaymentsInvoiceIdRouteImport } from './routes/payments.$invoiceId'
import { Route as MatchPerformanceMatchIdRouteImport } from './routes/match-performance.$matchId'
import { Route as DrillsNewRouteImport } from './routes/drills.new'
import { Route as AthletesAthleteIdRouteImport } from './routes/athletes.$athleteId'
import { Route as AssessmentImportRouteImport } from './routes/assessment.import'
import { Route as AssessmentAssessmentIdRouteImport } from './routes/assessment.$assessmentId'
import { Route as ProgramsProgramIdIndexRouteImport } from './routes/programs.$programId.index'
import { Route as DrillsDrillIdIndexRouteImport } from './routes/drills.$drillId.index'
import { Route as TrainingSessionIdPrintRouteImport } from './routes/training.$sessionId.print'
import { Route as ProgramsProgramIdEditRouteImport } from './routes/programs.$programId.edit'
import { Route as DrillsDrillIdEditRouteImport } from './routes/drills.$drillId.edit'

const UserManagementRoute = UserManagementRouteImport.update({
  id: '/user-management',
  path: '/user-management',
  getParentRoute: () => rootRouteImport,
} as any)
const TeamsRoute = TeamsRouteImport.update({
  id: '/teams',
  path: '/teams',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const ScheduleRoute = ScheduleRouteImport.update({
  id: '/schedule',
  path: '/schedule',
  getParentRoute: () => rootRouteImport,
} as any)
const RoleManagementRoute = RoleManagementRouteImport.update({
  id: '/role-management',
  path: '/role-management',
  getParentRoute: () => rootRouteImport,
} as any)
const RevenueRoute = RevenueRouteImport.update({
  id: '/revenue',
  path: '/revenue',
  getParentRoute: () => rootRouteImport,
} as any)
const ReportsRoute = ReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => rootRouteImport,
} as any)
const ProgressRoute = ProgressRouteImport.update({
  id: '/progress',
  path: '/progress',
  getParentRoute: () => rootRouteImport,
} as any)
const MyAthletesRoute = MyAthletesRouteImport.update({
  id: '/my-athletes',
  path: '/my-athletes',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const InsightsRoute = InsightsRouteImport.update({
  id: '/insights',
  path: '/insights',
  getParentRoute: () => rootRouteImport,
} as any)
const EvaluationsRoute = EvaluationsRouteImport.update({
  id: '/evaluations',
  path: '/evaluations',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const CoachesRoute = CoachesRouteImport.update({
  id: '/coaches',
  path: '/coaches',
  getParentRoute: () => rootRouteImport,
} as any)
const CoachFeedbackRoute = CoachFeedbackRouteImport.update({
  id: '/coach-feedback',
  path: '/coach-feedback',
  getParentRoute: () => rootRouteImport,
} as any)
const AttendanceRoute = AttendanceRouteImport.update({
  id: '/attendance',
  path: '/attendance',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const TrainingIndexRoute = TrainingIndexRouteImport.update({
  id: '/training/',
  path: '/training/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProgramsIndexRoute = ProgramsIndexRouteImport.update({
  id: '/programs/',
  path: '/programs/',
  getParentRoute: () => rootRouteImport,
} as any)
const PaymentsIndexRoute = PaymentsIndexRouteImport.update({
  id: '/payments/',
  path: '/payments/',
  getParentRoute: () => rootRouteImport,
} as any)
const MatchPerformanceIndexRoute = MatchPerformanceIndexRouteImport.update({
  id: '/match-performance/',
  path: '/match-performance/',
  getParentRoute: () => rootRouteImport,
} as any)
const DrillsIndexRoute = DrillsIndexRouteImport.update({
  id: '/drills/',
  path: '/drills/',
  getParentRoute: () => rootRouteImport,
} as any)
const AthletesIndexRoute = AthletesIndexRouteImport.update({
  id: '/athletes/',
  path: '/athletes/',
  getParentRoute: () => rootRouteImport,
} as any)
const AssessmentIndexRoute = AssessmentIndexRouteImport.update({
  id: '/assessment/',
  path: '/assessment/',
  getParentRoute: () => rootRouteImport,
} as any)
const TrainingSessionIdRoute = TrainingSessionIdRouteImport.update({
  id: '/training/$sessionId',
  path: '/training/$sessionId',
  getParentRoute: () => rootRouteImport,
} as any)
const ProgramsNewRoute = ProgramsNewRouteImport.update({
  id: '/programs/new',
  path: '/programs/new',
  getParentRoute: () => rootRouteImport,
} as any)
const PaymentsInvoiceIdRoute = PaymentsInvoiceIdRouteImport.update({
  id: '/payments/$invoiceId',
  path: '/payments/$invoiceId',
  getParentRoute: () => rootRouteImport,
} as any)
const MatchPerformanceMatchIdRoute = MatchPerformanceMatchIdRouteImport.update({
  id: '/match-performance/$matchId',
  path: '/match-performance/$matchId',
  getParentRoute: () => rootRouteImport,
} as any)
const DrillsNewRoute = DrillsNewRouteImport.update({
  id: '/drills/new',
  path: '/drills/new',
  getParentRoute: () => rootRouteImport,
} as any)
const AthletesAthleteIdRoute = AthletesAthleteIdRouteImport.update({
  id: '/athletes/$athleteId',
  path: '/athletes/$athleteId',
  getParentRoute: () => rootRouteImport,
} as any)
const AssessmentImportRoute = AssessmentImportRouteImport.update({
  id: '/assessment/import',
  path: '/assessment/import',
  getParentRoute: () => rootRouteImport,
} as any)
const AssessmentAssessmentIdRoute = AssessmentAssessmentIdRouteImport.update({
  id: '/assessment/$assessmentId',
  path: '/assessment/$assessmentId',
  getParentRoute: () => rootRouteImport,
} as any)
const ProgramsProgramIdIndexRoute = ProgramsProgramIdIndexRouteImport.update({
  id: '/programs/$programId/',
  path: '/programs/$programId/',
  getParentRoute: () => rootRouteImport,
} as any)
const DrillsDrillIdIndexRoute = DrillsDrillIdIndexRouteImport.update({
  id: '/drills/$drillId/',
  path: '/drills/$drillId/',
  getParentRoute: () => rootRouteImport,
} as any)
const TrainingSessionIdPrintRoute = TrainingSessionIdPrintRouteImport.update({
  id: '/print',
  path: '/print',
  getParentRoute: () => TrainingSessionIdRoute,
} as any)
const ProgramsProgramIdEditRoute = ProgramsProgramIdEditRouteImport.update({
  id: '/programs/$programId/edit',
  path: '/programs/$programId/edit',
  getParentRoute: () => rootRouteImport,
} as any)
const DrillsDrillIdEditRoute = DrillsDrillIdEditRouteImport.update({
  id: '/drills/$drillId/edit',
  path: '/drills/$drillId/edit',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/attendance': typeof AttendanceRoute
  '/coach-feedback': typeof CoachFeedbackRoute
  '/coaches': typeof CoachesRoute
  '/dashboard': typeof DashboardRoute
  '/evaluations': typeof EvaluationsRoute
  '/insights': typeof InsightsRoute
  '/login': typeof LoginRoute
  '/my-athletes': typeof MyAthletesRoute
  '/progress': typeof ProgressRoute
  '/reports': typeof ReportsRoute
  '/revenue': typeof RevenueRoute
  '/role-management': typeof RoleManagementRoute
  '/schedule': typeof ScheduleRoute
  '/settings': typeof SettingsRoute
  '/teams': typeof TeamsRoute
  '/user-management': typeof UserManagementRoute
  '/assessment/$assessmentId': typeof AssessmentAssessmentIdRoute
  '/assessment/import': typeof AssessmentImportRoute
  '/athletes/$athleteId': typeof AthletesAthleteIdRoute
  '/drills/new': typeof DrillsNewRoute
  '/match-performance/$matchId': typeof MatchPerformanceMatchIdRoute
  '/payments/$invoiceId': typeof PaymentsInvoiceIdRoute
  '/programs/new': typeof ProgramsNewRoute
  '/training/$sessionId': typeof TrainingSessionIdRouteWithChildren
  '/assessment/': typeof AssessmentIndexRoute
  '/athletes/': typeof AthletesIndexRoute
  '/drills/': typeof DrillsIndexRoute
  '/match-performance/': typeof MatchPerformanceIndexRoute
  '/payments/': typeof PaymentsIndexRoute
  '/programs/': typeof ProgramsIndexRoute
  '/training/': typeof TrainingIndexRoute
  '/drills/$drillId/edit': typeof DrillsDrillIdEditRoute
  '/programs/$programId/edit': typeof ProgramsProgramIdEditRoute
  '/training/$sessionId/print': typeof TrainingSessionIdPrintRoute
  '/drills/$drillId/': typeof DrillsDrillIdIndexRoute
  '/programs/$programId/': typeof ProgramsProgramIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/attendance': typeof AttendanceRoute
  '/coach-feedback': typeof CoachFeedbackRoute
  '/coaches': typeof CoachesRoute
  '/dashboard': typeof DashboardRoute
  '/evaluations': typeof EvaluationsRoute
  '/insights': typeof InsightsRoute
  '/login': typeof LoginRoute
  '/my-athletes': typeof MyAthletesRoute
  '/progress': typeof ProgressRoute
  '/reports': typeof ReportsRoute
  '/revenue': typeof RevenueRoute
  '/role-management': typeof RoleManagementRoute
  '/schedule': typeof ScheduleRoute
  '/settings': typeof SettingsRoute
  '/teams': typeof TeamsRoute
  '/user-management': typeof UserManagementRoute
  '/assessment/$assessmentId': typeof AssessmentAssessmentIdRoute
  '/assessment/import': typeof AssessmentImportRoute
  '/athletes/$athleteId': typeof AthletesAthleteIdRoute
  '/drills/new': typeof DrillsNewRoute
  '/match-performance/$matchId': typeof MatchPerformanceMatchIdRoute
  '/payments/$invoiceId': typeof PaymentsInvoiceIdRoute
  '/programs/new': typeof ProgramsNewRoute
  '/training/$sessionId': typeof TrainingSessionIdRouteWithChildren
  '/assessment': typeof AssessmentIndexRoute
  '/athletes': typeof AthletesIndexRoute
  '/drills': typeof DrillsIndexRoute
  '/match-performance': typeof MatchPerformanceIndexRoute
  '/payments': typeof PaymentsIndexRoute
  '/programs': typeof ProgramsIndexRoute
  '/training': typeof TrainingIndexRoute
  '/drills/$drillId/edit': typeof DrillsDrillIdEditRoute
  '/programs/$programId/edit': typeof ProgramsProgramIdEditRoute
  '/training/$sessionId/print': typeof TrainingSessionIdPrintRoute
  '/drills/$drillId': typeof DrillsDrillIdIndexRoute
  '/programs/$programId': typeof ProgramsProgramIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/attendance': typeof AttendanceRoute
  '/coach-feedback': typeof CoachFeedbackRoute
  '/coaches': typeof CoachesRoute
  '/dashboard': typeof DashboardRoute
  '/evaluations': typeof EvaluationsRoute
  '/insights': typeof InsightsRoute
  '/login': typeof LoginRoute
  '/my-athletes': typeof MyAthletesRoute
  '/progress': typeof ProgressRoute
  '/reports': typeof ReportsRoute
  '/revenue': typeof RevenueRoute
  '/role-management': typeof RoleManagementRoute
  '/schedule': typeof ScheduleRoute
  '/settings': typeof SettingsRoute
  '/teams': typeof TeamsRoute
  '/user-management': typeof UserManagementRoute
  '/assessment/$assessmentId': typeof AssessmentAssessmentIdRoute
  '/assessment/import': typeof AssessmentImportRoute
  '/athletes/$athleteId': typeof AthletesAthleteIdRoute
  '/drills/new': typeof DrillsNewRoute
  '/match-performance/$matchId': typeof MatchPerformanceMatchIdRoute
  '/payments/$invoiceId': typeof PaymentsInvoiceIdRoute
  '/programs/new': typeof ProgramsNewRoute
  '/training/$sessionId': typeof TrainingSessionIdRouteWithChildren
  '/assessment/': typeof AssessmentIndexRoute
  '/athletes/': typeof AthletesIndexRoute
  '/drills/': typeof DrillsIndexRoute
  '/match-performance/': typeof MatchPerformanceIndexRoute
  '/payments/': typeof PaymentsIndexRoute
  '/programs/': typeof ProgramsIndexRoute
  '/training/': typeof TrainingIndexRoute
  '/drills/$drillId/edit': typeof DrillsDrillIdEditRoute
  '/programs/$programId/edit': typeof ProgramsProgramIdEditRoute
  '/training/$sessionId/print': typeof TrainingSessionIdPrintRoute
  '/drills/$drillId/': typeof DrillsDrillIdIndexRoute
  '/programs/$programId/': typeof ProgramsProgramIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/attendance'
    | '/coach-feedback'
    | '/coaches'
    | '/dashboard'
    | '/evaluations'
    | '/insights'
    | '/login'
    | '/my-athletes'
    | '/progress'
    | '/reports'
    | '/revenue'
    | '/role-management'
    | '/schedule'
    | '/settings'
    | '/teams'
    | '/user-management'
    | '/assessment/$assessmentId'
    | '/assessment/import'
    | '/athletes/$athleteId'
    | '/drills/new'
    | '/match-performance/$matchId'
    | '/payments/$invoiceId'
    | '/programs/new'
    | '/training/$sessionId'
    | '/assessment/'
    | '/athletes/'
    | '/drills/'
    | '/match-performance/'
    | '/payments/'
    | '/programs/'
    | '/training/'
    | '/drills/$drillId/edit'
    | '/programs/$programId/edit'
    | '/training/$sessionId/print'
    | '/drills/$drillId/'
    | '/programs/$programId/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/attendance'
    | '/coach-feedback'
    | '/coaches'
    | '/dashboard'
    | '/evaluations'
    | '/insights'
    | '/login'
    | '/my-athletes'
    | '/progress'
    | '/reports'
    | '/revenue'
    | '/role-management'
    | '/schedule'
    | '/settings'
    | '/teams'
    | '/user-management'
    | '/assessment/$assessmentId'
    | '/assessment/import'
    | '/athletes/$athleteId'
    | '/drills/new'
    | '/match-performance/$matchId'
    | '/payments/$invoiceId'
    | '/programs/new'
    | '/training/$sessionId'
    | '/assessment'
    | '/athletes'
    | '/drills'
    | '/match-performance'
    | '/payments'
    | '/programs'
    | '/training'
    | '/drills/$drillId/edit'
    | '/programs/$programId/edit'
    | '/training/$sessionId/print'
    | '/drills/$drillId'
    | '/programs/$programId'
  id:
    | '__root__'
    | '/'
    | '/attendance'
    | '/coach-feedback'
    | '/coaches'
    | '/dashboard'
    | '/evaluations'
    | '/insights'
    | '/login'
    | '/my-athletes'
    | '/progress'
    | '/reports'
    | '/revenue'
    | '/role-management'
    | '/schedule'
    | '/settings'
    | '/teams'
    | '/user-management'
    | '/assessment/$assessmentId'
    | '/assessment/import'
    | '/athletes/$athleteId'
    | '/drills/new'
    | '/match-performance/$matchId'
    | '/payments/$invoiceId'
    | '/programs/new'
    | '/training/$sessionId'
    | '/assessment/'
    | '/athletes/'
    | '/drills/'
    | '/match-performance/'
    | '/payments/'
    | '/programs/'
    | '/training/'
    | '/drills/$drillId/edit'
    | '/programs/$programId/edit'
    | '/training/$sessionId/print'
    | '/drills/$drillId/'
    | '/programs/$programId/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AttendanceRoute: typeof AttendanceRoute
  CoachFeedbackRoute: typeof CoachFeedbackRoute
  CoachesRoute: typeof CoachesRoute
  DashboardRoute: typeof DashboardRoute
  EvaluationsRoute: typeof EvaluationsRoute
  InsightsRoute: typeof InsightsRoute
  LoginRoute: typeof LoginRoute
  MyAthletesRoute: typeof MyAthletesRoute
  ProgressRoute: typeof ProgressRoute
  ReportsRoute: typeof ReportsRoute
  RevenueRoute: typeof RevenueRoute
  RoleManagementRoute: typeof RoleManagementRoute
  ScheduleRoute: typeof ScheduleRoute
  SettingsRoute: typeof SettingsRoute
  TeamsRoute: typeof TeamsRoute
  UserManagementRoute: typeof UserManagementRoute
  AssessmentAssessmentIdRoute: typeof AssessmentAssessmentIdRoute
  AssessmentImportRoute: typeof AssessmentImportRoute
  AthletesAthleteIdRoute: typeof AthletesAthleteIdRoute
  DrillsNewRoute: typeof DrillsNewRoute
  MatchPerformanceMatchIdRoute: typeof MatchPerformanceMatchIdRoute
  PaymentsInvoiceIdRoute: typeof PaymentsInvoiceIdRoute
  ProgramsNewRoute: typeof ProgramsNewRoute
  TrainingSessionIdRoute: typeof TrainingSessionIdRouteWithChildren
  AssessmentIndexRoute: typeof AssessmentIndexRoute
  AthletesIndexRoute: typeof AthletesIndexRoute
  DrillsIndexRoute: typeof DrillsIndexRoute
  MatchPerformanceIndexRoute: typeof MatchPerformanceIndexRoute
  PaymentsIndexRoute: typeof PaymentsIndexRoute
  ProgramsIndexRoute: typeof ProgramsIndexRoute
  TrainingIndexRoute: typeof TrainingIndexRoute
  DrillsDrillIdEditRoute: typeof DrillsDrillIdEditRoute
  ProgramsProgramIdEditRoute: typeof ProgramsProgramIdEditRoute
  DrillsDrillIdIndexRoute: typeof DrillsDrillIdIndexRoute
  ProgramsProgramIdIndexRoute: typeof ProgramsProgramIdIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/user-management': {
      id: '/user-management'
      path: '/user-management'
      fullPath: '/user-management'
      preLoaderRoute: typeof UserManagementRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/teams': {
      id: '/teams'
      path: '/teams'
      fullPath: '/teams'
      preLoaderRoute: typeof TeamsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/schedule': {
      id: '/schedule'
      path: '/schedule'
      fullPath: '/schedule'
      preLoaderRoute: typeof ScheduleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/role-management': {
      id: '/role-management'
      path: '/role-management'
      fullPath: '/role-management'
      preLoaderRoute: typeof RoleManagementRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/revenue': {
      id: '/revenue'
      path: '/revenue'
      fullPath: '/revenue'
      preLoaderRoute: typeof RevenueRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reports': {
      id: '/reports'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof ReportsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/progress': {
      id: '/progress'
      path: '/progress'
      fullPath: '/progress'
      preLoaderRoute: typeof ProgressRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/my-athletes': {
      id: '/my-athletes'
      path: '/my-athletes'
      fullPath: '/my-athletes'
      preLoaderRoute: typeof MyAthletesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/insights': {
      id: '/insights'
      path: '/insights'
      fullPath: '/insights'
      preLoaderRoute: typeof InsightsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/evaluations': {
      id: '/evaluations'
      path: '/evaluations'
      fullPath: '/evaluations'
      preLoaderRoute: typeof EvaluationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/coaches': {
      id: '/coaches'
      path: '/coaches'
      fullPath: '/coaches'
      preLoaderRoute: typeof CoachesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/coach-feedback': {
      id: '/coach-feedback'
      path: '/coach-feedback'
      fullPath: '/coach-feedback'
      preLoaderRoute: typeof CoachFeedbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/attendance': {
      id: '/attendance'
      path: '/attendance'
      fullPath: '/attendance'
      preLoaderRoute: typeof AttendanceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/training/': {
      id: '/training/'
      path: '/training'
      fullPath: '/training/'
      preLoaderRoute: typeof TrainingIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/programs/': {
      id: '/programs/'
      path: '/programs'
      fullPath: '/programs/'
      preLoaderRoute: typeof ProgramsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/payments/': {
      id: '/payments/'
      path: '/payments'
      fullPath: '/payments/'
      preLoaderRoute: typeof PaymentsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/match-performance/': {
      id: '/match-performance/'
      path: '/match-performance'
      fullPath: '/match-performance/'
      preLoaderRoute: typeof MatchPerformanceIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/drills/': {
      id: '/drills/'
      path: '/drills'
      fullPath: '/drills/'
      preLoaderRoute: typeof DrillsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/athletes/': {
      id: '/athletes/'
      path: '/athletes'
      fullPath: '/athletes/'
      preLoaderRoute: typeof AthletesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/assessment/': {
      id: '/assessment/'
      path: '/assessment'
      fullPath: '/assessment/'
      preLoaderRoute: typeof AssessmentIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/training/$sessionId': {
      id: '/training/$sessionId'
      path: '/training/$sessionId'
      fullPath: '/training/$sessionId'
      preLoaderRoute: typeof TrainingSessionIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/programs/new': {
      id: '/programs/new'
      path: '/programs/new'
      fullPath: '/programs/new'
      preLoaderRoute: typeof ProgramsNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/payments/$invoiceId': {
      id: '/payments/$invoiceId'
      path: '/payments/$invoiceId'
      fullPath: '/payments/$invoiceId'
      preLoaderRoute: typeof PaymentsInvoiceIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/match-performance/$matchId': {
      id: '/match-performance/$matchId'
      path: '/match-performance/$matchId'
      fullPath: '/match-performance/$matchId'
      preLoaderRoute: typeof MatchPerformanceMatchIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/drills/new': {
      id: '/drills/new'
      path: '/drills/new'
      fullPath: '/drills/new'
      preLoaderRoute: typeof DrillsNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/athletes/$athleteId': {
      id: '/athletes/$athleteId'
      path: '/athletes/$athleteId'
      fullPath: '/athletes/$athleteId'
      preLoaderRoute: typeof AthletesAthleteIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/assessment/import': {
      id: '/assessment/import'
      path: '/assessment/import'
      fullPath: '/assessment/import'
      preLoaderRoute: typeof AssessmentImportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/assessment/$assessmentId': {
      id: '/assessment/$assessmentId'
      path: '/assessment/$assessmentId'
      fullPath: '/assessment/$assessmentId'
      preLoaderRoute: typeof AssessmentAssessmentIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/programs/$programId/': {
      id: '/programs/$programId/'
      path: '/programs/$programId'
      fullPath: '/programs/$programId/'
      preLoaderRoute: typeof ProgramsProgramIdIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/drills/$drillId/': {
      id: '/drills/$drillId/'
      path: '/drills/$drillId'
      fullPath: '/drills/$drillId/'
      preLoaderRoute: typeof DrillsDrillIdIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/training/$sessionId/print': {
      id: '/training/$sessionId/print'
      path: '/print'
      fullPath: '/training/$sessionId/print'
      preLoaderRoute: typeof TrainingSessionIdPrintRouteImport
      parentRoute: typeof TrainingSessionIdRoute
    }
    '/programs/$programId/edit': {
      id: '/programs/$programId/edit'
      path: '/programs/$programId/edit'
      fullPath: '/programs/$programId/edit'
      preLoaderRoute: typeof ProgramsProgramIdEditRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/drills/$drillId/edit': {
      id: '/drills/$drillId/edit'
      path: '/drills/$drillId/edit'
      fullPath: '/drills/$drillId/edit'
      preLoaderRoute: typeof DrillsDrillIdEditRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface TrainingSessionIdRouteChildren {
  TrainingSessionIdPrintRoute: typeof TrainingSessionIdPrintRoute
}

const TrainingSessionIdRouteChildren: TrainingSessionIdRouteChildren = {
  TrainingSessionIdPrintRoute: TrainingSessionIdPrintRoute,
}

const TrainingSessionIdRouteWithChildren =
  TrainingSessionIdRoute._addFileChildren(TrainingSessionIdRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AttendanceRoute: AttendanceRoute,
  CoachFeedbackRoute: CoachFeedbackRoute,
  CoachesRoute: CoachesRoute,
  DashboardRoute: DashboardRoute,
  EvaluationsRoute: EvaluationsRoute,
  InsightsRoute: InsightsRoute,
  LoginRoute: LoginRoute,
  MyAthletesRoute: MyAthletesRoute,
  ProgressRoute: ProgressRoute,
  ReportsRoute: ReportsRoute,
  RevenueRoute: RevenueRoute,
  RoleManagementRoute: RoleManagementRoute,
  ScheduleRoute: ScheduleRoute,
  SettingsRoute: SettingsRoute,
  TeamsRoute: TeamsRoute,
  UserManagementRoute: UserManagementRoute,
  AssessmentAssessmentIdRoute: AssessmentAssessmentIdRoute,
  AssessmentImportRoute: AssessmentImportRoute,
  AthletesAthleteIdRoute: AthletesAthleteIdRoute,
  DrillsNewRoute: DrillsNewRoute,
  MatchPerformanceMatchIdRoute: MatchPerformanceMatchIdRoute,
  PaymentsInvoiceIdRoute: PaymentsInvoiceIdRoute,
  ProgramsNewRoute: ProgramsNewRoute,
  TrainingSessionIdRoute: TrainingSessionIdRouteWithChildren,
  AssessmentIndexRoute: AssessmentIndexRoute,
  AthletesIndexRoute: AthletesIndexRoute,
  DrillsIndexRoute: DrillsIndexRoute,
  MatchPerformanceIndexRoute: MatchPerformanceIndexRoute,
  PaymentsIndexRoute: PaymentsIndexRoute,
  ProgramsIndexRoute: ProgramsIndexRoute,
  TrainingIndexRoute: TrainingIndexRoute,
  DrillsDrillIdEditRoute: DrillsDrillIdEditRoute,
  ProgramsProgramIdEditRoute: ProgramsProgramIdEditRoute,
  DrillsDrillIdIndexRoute: DrillsDrillIdIndexRoute,
  ProgramsProgramIdIndexRoute: ProgramsProgramIdIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
